// MyMiniProject/angular-dotnet-finance/frontend/src/app/components/layout/layout.component.ts
import { Component, inject } from '@angular/core';
import { Router, RouterLink, RouterLinkActive, RouterOutlet } from '@angular/router';
import { AuthService } from '../../core/auth.service';

@Component({
  selector: 'app-layout',
  standalone: true,
  imports: [RouterOutlet, RouterLink, RouterLinkActive],
  templateUrl: './layout.component.html',
})
export class LayoutComponent {
  readonly auth = inject(AuthService);
  private readonly router = inject(Router);

  handleLogout(): void {
    this.auth.logout();
    this.router.navigate(['/login']);
  }
}

<div class="shell">
  <aside class="side">
    <div class="brand">
      <span class="brand-mark">฿</span>
      <div>
        <strong>Ledger</strong>
        <small>รายรับรายจ่าย</small>
      </div>
    </div>
    <nav>
      <a routerLink="/" routerLinkActive="active" [routerLinkActiveOptions]="{ exact: true }">แดชบอร์ด</a>
      <a routerLink="/transactions" routerLinkActive="active">รายการ</a>
      @if (auth.isAdmin()) {
        <a routerLink="/users" routerLinkActive="active">ผู้ใช้</a>
      }
    </nav>
    <div class="side-foot">
      <div class="who">
        <strong>{{ auth.user()?.fullName }}</strong>
        <span>{{ auth.user()?.role === 'admin' ? 'ผู้ดูแล' : 'ผู้ใช้' }}</span>
      </div>
      <button type="button" class="btn ghost" (click)="handleLogout()">ออกจากระบบ</button>
    </div>
  </aside>
  <main class="main">
    <router-outlet />
  </main>
</div>

// MyMiniProject/react-dotnet-finance/frontend/src/components/Layout.jsx
import { NavLink, Outlet, useNavigate } from 'react-router-dom'
import { useAuth } from '../auth'

export default function Layout() {
  const { user, logout, isAdmin } = useAuth()
  const navigate = useNavigate()

  function handleLogout() {
    logout()
    navigate('/login')
  }

  return (
    <div className="shell">
      <aside className="side">
        <div className="brand">
          <span className="brand-mark">฿</span>
          <div>
            <strong>Ledger</strong>
            <small>รายรับรายจ่าย</small>
          </div>
        </div>
        <nav>
          <NavLink to="/" end>
            แดชบอร์ด
          </NavLink>
          <NavLink to="/transactions">รายการ</NavLink>
          {isAdmin && <NavLink to="/users">ผู้ใช้</NavLink>}
        </nav>
        <div className="side-foot">
          <div className="who">
            <strong>{user?.fullName}</strong>
            <span>{user?.role === 'admin' ? 'ผู้ดูแล' : 'ผู้ใช้'}</span>
          </div>
          <button type="button" className="btn ghost" onClick={handleLogout}>
            ออกจากระบบ
          </button>
        </div>
      </aside>
      <main className="main">
        <Outlet />
      </main>
    </div>
  )
}
